// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  alternate_grid_2: dynamic(() => import("./AlternateGrid2")),
  header: dynamic(() => import("./Header")),
  relation_contenu: dynamic(() => import("./RelationContenu")),
  rich_text: dynamic(() => import("./RichText")),
};
